import os
import requests
from PIL import Image

# Load API Key
HUGGINGFACE_API_KEY = os.getenv("HUGGINGFACEHUB_API_TOKEN")
if not HUGGINGFACE_API_KEY:
    raise ValueError("HUGGINGFACEHUB_API_TOKEN is not set in the .env file.")

def get_image_caption(image_path):
    """
    Generates a caption for the given image using Hugging Face's BLIP model.
    Args:
        image_path (str): Path to the image file.
    Returns:
        str: Caption generated by the model.
    """
    api_url = "https://api-inference.huggingface.co/models/Salesforce/blip-image-captioning-base"
    headers = {"Authorization": f"Bearer {HUGGINGFACE_API_KEY}"}

    # Open the image file
    with open(image_path, "rb") as image_file:
        image_data = image_file.read()

    # Send the image to the Hugging Face API
    response = requests.post(api_url, headers=headers, data=image_data)

    # Process the response
    if response.status_code == 200:
        result = response.json()
        return result[0]["generated_text"]  # The caption
    else:
        raise Exception(f"API request failed with status {response.status_code}: {response.text}")
